/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class Moviedata extends javax.swing.JFrame {

    /** Creates new form Moviedata */
    public Moviedata() {
        initComponents();
        datatable();
    }
    
    private void datatable() {
        DefaultTableModel tb1 = new DefaultTableModel();
        tb1.addColumn("Judul");
        tb1.addColumn("Alur");
        tb1.addColumn("Penokohan");
        tb1.addColumn("Akting");
        tb1.addColumn("Nilai");
        tb_movie.setModel(tb1);
        try{
            statement = (Statement) konek.getConnection().createStatement();
            ResultSet res;
            res = statement.executeQuery("Select * from movie");
            while (res.next())
            {
                tb1.addRow(new Object []{
                    res.getString("judul"),
                    res.getString("alur"),
                    res.getString("penokohan"),
                    res.getString("akting"),
                    res.getString("nilai"),
                });
                isitable.setModel(tb1);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        isitable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtjudul = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtalur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpenokohan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtakting = new javax.swing.JTextField();
        btntambah = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        isitable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Judul", "Alur", "Penokohan", "Akting", "Rating"
            }
        ));
        isitable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isitableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(isitable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Judul");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Alur");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Penokohan");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Akting");

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 375, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jLabel1)
                        .add(txtjudul, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .add(jLabel2)
                        .add(jLabel3)
                        .add(jLabel4)
                        .add(txtalur)
                        .add(txtpenokohan)
                        .add(txtakting))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btnclear, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btndelete, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btnupdate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btntambah, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtjudul, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtalur, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtpenokohan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtakting, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(btntambah)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnupdate)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btndelete))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnclear)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        int akting = parseInt(txtakting.getText());
        int alur = parseInt(txtalur.getText());
        String judul = txtjudul.getText();
        int penokohan = parseInt(txtpenokohan.getText());
        int nilai = (alur+akting+penokohan)/3;
        
        if(alur > 5 || penokohan > 5 || akting > 5){
               JOptionPane.showMessageDialog(null,"Maksimal alur, penokohan, dan akting adalah 5!"); 
            } else if(alur < 0 || penokohan < 0 || akting < 0){
                JOptionPane.showMessageDialog(null,"Minimal alur, penokohan, dan akting adalah 0!");
            } else{
                try{
                Statement statement = (Statement) konek.getConnection().createStatement();
                statement.executeUpdate("INSERT INTO `movie` (`judul`, `alur`, `penokohan`, `akting`, `nilai`) VALUES ('" + txtjudul.getText() + "', '" + txtalur.getText() + "', '" + txtpenokohan.getText() + "', '" + txtakting.getText() + "', '"+ nilai + "')");
                statement.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil disimpan");
                }catch (Exception t){
                    JOptionPane.showMessageDialog(null, "Data sudah ada");
                }
            }
    datatable();
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        if(btnupdate.getText() == "btnupdate"){
           txtjudul.requestFocus();
        }else{
            int akting = parseInt(txtakting.getText());
            int alur = parseInt(txtalur.getText());
            String judul = txtjudul.getText();
            int penokohan = parseInt(txtpenokohan.getText());
            int nilai = (alur+akting+penokohan)/3;
            
        if(alur > 5.0 || penokohan > 5.0 || akting > 5.0){
               JOptionPane.showMessageDialog(null,"Maksimal alur, penokohan, dan akting adalah 5!"); 
            } else if(alur < 0 || penokohan < 0 || akting < 0){
                JOptionPane.showMessageDialog(null,"Minimal alur, penokohan, dan akting adalah 0!");
            } else{
                    try{
                        Statement statement = (Statement) konek.getConnection().createStatement();
                        statement.executeUpdate("UPDATE `movie` SET `judul` = '"+txtjudul.getText()+"', `alur` = '"+txtalur.getText()+"', `penokohan` = '"+txtpenokohan.getText()+"'"
                                + ", `akting` = '"+txtakting.getText()+"', `nilai` = '"+nilai+"' WHERE `movie`.`judul` = '"+judul+"';");
                        statement.close();
                        JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
                        }catch (Exception t){
                        JOptionPane.showMessageDialog(null, "Data Gagal diubah");
                        }
                    }
        datatable();
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
            String akting = txtakting.getText();
            String alur = txtalur.getText();
            String judul = txtjudul.getText();
            String penokohan = txtpenokohan.getText();
            String nilai = String.valueOf((Integer.parseInt(alur)+Integer.parseInt(akting)+Integer.parseInt(penokohan))/3);
        try{
            Statement statement = (Statement) konek.getConnection().createStatement();
            statement.executeUpdate("delete from movie where judul = '" +judul+ "';");
            JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");
            txtjudul.setText("");
            txtalur.setText("");
            txtpenokohan.setText("");
            txtakting.setText("");
            txtjudul.requestFocus();
        }catch (Exception t){
            JOptionPane.showMessageDialog(null, "Data Gagal di Hapus");
        }
        datatable();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtjudul.setText(" "); 
        txtakting.setText(" "); 
        txtalur.setText(" ");
        txtpenokohan.setText(" "); 
        String nilai = String.valueOf(" ");
    }//GEN-LAST:event_btnclearActionPerformed

    private void isitableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isitableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)this.isitable.getModel();
        Object title = model.getValueAt(this.isitable.getSelectedRow(), 0);
        Object story = model.getValueAt(this.isitable.getSelectedRow(), 1);
        Object actors = model.getValueAt(this.isitable.getSelectedRow(), 2);
        Object acting = model.getValueAt(this.isitable.getSelectedRow(), 3);

        this.txtjudul.setText(title.toString());
        this.txtalur.setText(story.toString());
        this.txtpenokohan.setText(actors.toString());
        this.txtakting.setText(acting.toString());
    }//GEN-LAST:event_isitableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Moviedata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Moviedata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Moviedata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Moviedata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Moviedata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnupdate;
    private javax.swing.JTable isitable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtakting;
    private javax.swing.JTextField txtalur;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtpenokohan;
    // End of variables declaration//GEN-END:variables

}
